### ISSUE TITLE
ObjectDisposedException cannot be deserialized

### ISSUE THREAD

**Issue by ZoolWay** [akkadotnet/Hyperion#64]
Hyperion does not seem to deserialize `ObjectDisposedException`. Got many problems because it was wrapped in some messages containing the Exception but could reproduce it in the end with this simple lines:

```
var message = new ObjectDisposedException("oh no");
var serializer = system.Serialization.FindSerializerFor(message);
var binary = serializer.ToBinary(message);
var msg = serializer.FromBinary(binary, null);
```

Error is:

> An exception occurred, System.MissingMethodException: No parameterless constructor defined for this object.

The error feels misleading as most immutable Akka messages do not have a parameterless constructor. Also it does not mention the class where it misses the constructor. I wrapped the `Akka.Serialization.HyperionSerializer` with my own Akka serializer but I could also track the outer-most parent class. That was in my case `Akka.Actor.Status.Failure` so it took my a while to go down to `ObjectDisposedException`.

Versions:
- Akka 1.2.3
- Akka Remote 1.2.3
- Akka.Serialization.Hyperion 1.2.3.43-beta
- Hyperion 0.9.2

A temporary workaround to replace those instances with `null` would be appreciated.

**Comment by ZoolWay** [comment]
An example repo can be found here: https://github.com/telecomsoftware/sample-akka-hyperion-i64

Especially:
https://github.com/telecomsoftware/sample-akka-hyperion-i64/blob/master/AkkaStreams/Service.cs#L23-L27
And here for more advanced scenarios:
https://github.com/telecomsoftware/sample-akka-hyperion-i64/blob/master/AkkaStreams/SenderActor.cs#L35-L36
https://github.com/telecomsoftware/sample-akka-hyperion-i64/blob/master/AkkaStreams/SenderActor.cs#L39

**Comment by yallie** [comment]
`TargetInvocationException` also cannot be deserialized because of the missing default constructor.

**Comment by yallie** [comment]
`FormatterServices.GetUninitializedObject` can be used instead of `Activator.CreateInstance` when the parameterless constructor is not defined. This method exists in .NET Core, but is not currently exposed. This API is planned to be made public asap, [see dotnet corefx issue #8133](https://github.com/dotnet/corefx/issues/8133).

The current workaround is to invoke this method using Reflection [as demonstrated in this related discussion](https://github.com/dotnet/corefx/issues/7938#issuecomment-227580931) by Orlean framework developer. I tried this approach and it seems to work just fine for exception types not having a default constructor.

**Comment by yallie** [comment]
I guess this issue can now be closed.
