### ISSUE TITLE
Implement support for IDictionary<TKey,TValue>

### ISSUE THREAD

**Issue by ArturChe** [akkadotnet/Hyperion#99]
I have Akka.Serialization.Hyperion 1.3.2-beta54 and Hyperion 0.9.6.
On that versions I'm getting an error: Generic IDictionary<TKey,TValue> are not yet supported .
When I can expect the support will be provided?

**Comment by Arkatufus** [comment]
We really need support for generic dictionary collection so that we can use the new standalone Hocon library with Akka.Net.

`System.Runtime.Serialization.SerializationException : Generic IDictionary<TKey,TValue> are not yet supported
---- System.NotSupportedException : Generic IDictionary<TKey,TValue> are not yet supported`
